server:
  port: 8081

kafka:
  general:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

  simple:
    group-id: ${GROUP_ID:test-group}
    topic: ${KAFKA_DEFAULT_TOPIC:simple-random-topic}

  orders:
    group-id: ${GROUP_ID:objects-group}
    topic: ${KAFKA_DEFAULT_TOPIC:domain-orders-topic}


# config for autoconfiguration via application .yaml
#spring:
#  kafka:
#    bootstrap-servers:
#      - localhost:9092
#      - localhost:9093
#      - localhost:9094
#    consumer:
#      group-id: random-consumer
#      auto-offset-reset: earliest
#      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-serializer: org.apache.kafka.common.serialization.StringDeserializer

message:
  processing:
    time: 0