server:
  port: 8080

# custom configuration via Configuration files
kafka:
  general:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

  simple:
    topic: ${KAFKA_DEFAULT_TOPIC:simple-random-topic}

  orders:
    topic: ${KAFKA_DEFAULT_TOPIC:domain-orders-topic}

# config for autoconfiguration via application .yaml
#spring:
#  kafka:
#    bootstrap-servers:
#      - localhost:9092
#      - localhost:9093
#      - localhost:9094
#    template:
#      default-topic: random-number
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer